/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 26
#define YY_END_OF_BUFFER 27
static yyconst short int yy_accept[298] =
    {   0,
        4,    4,   27,   25,   26,   25,   20,   21,    7,    6,
        8,    9,    1,   10,   12,   11,    2,    2,    2,    2,
        2,   18,   25,   19,   16,   13,   15,   14,    0,    0,
        2,    0,    2,    2,    2,    2,    2,   17,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    2,    2,
        0,    2,    0,    0,    0,    0,    0,    5,    0,    2,
        2,    0,    2,    3,    0,    0,    4,    3,    2,    0,
        0,    0,    2,    3,    0,    0,    3,    2,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    2,    2,    2,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    2,    0,    2,    2,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    2,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        5,    2,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    2,    0,    0,   23,    0,    0,    0,    0,
        0,    0,    2,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   24,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   22,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   23,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    1,    1,    1,    1,    4,    1,    5,
        6,    7,    8,    9,   10,    1,   11,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   13,   14,   15,
       16,   17,    1,    1,   18,   19,   20,   21,   22,   23,
       19,   24,   25,   19,   19,   26,   19,   27,   28,   19,
       19,   29,   30,   19,   19,   31,   32,   19,   19,   19,
        1,    1,    1,    1,    1,    1,   19,   19,   19,   19,

       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   33,   19,   19,   19,   19,   19,
       19,   19,   34,   35,   36,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[37] =
    {   0,
        1,    1,    1,    1,    1,    2,    1,    3,    4,    1,
        1,    5,    6,    7,    1,    1,    1,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    1,    1,    9
    } ;

static yyconst short int yy_base[371] =
    {   0,
        0,    0,  843,  844,  844,  838,  844,  844,  844,  844,
      844,  844,  844,  825,  824,  823,   29,   31,   19,   20,
       21,  844,  803,  844,  844,  844,  844,  844,   62,    0,
      809,    0,   95,   23,   26,   47,   28,  844,  820,  831,
       47,   52,  818,   55,  798,   45,  818,   53,   46,   53,
        0,   61,   59,    0,   70,   81,  817,  816,   83,   81,
       86,   88,   79,  815,  106,  113,  808,  115,  103,  130,
      109,  163,  108,  813,  135,  144,  812,  191,  809,  820,
      116,  142,  807,  143,  787,  127,    0,  222,    0,  791,
        0,  255,  127,  173,  175,  288,  131,    0,  154,  161,

      799,  808,  177,  181,  790,  185,  768,  178,  784,  184,
      133,    0,  767,    0,    0,  184,  785,  203,  321,  187,
      354,  208,    0,  209,  222,  772,  765,  211,  214,  233,
      762,  222,  735,  759,  756,  740,  747,  215,  244,  727,
      245,  705,  242,  721,  242,  255,  262,  267,  272,  718,
       86,  185,  220,  261,    0,  274,  714,  713,  288,  297,
      280,  299,  291,  308,  326,  703,  718,  307,    0,  331,
        0,  334,  694,  387,    0,  692,    0,  420,  259,  692,
      683,  708,  702,  333,  685,  339,  677,  685,  294,  334,
      669,  360,  647,  360,  664,  341,  292,  643,  294,  365,

      370,  658,  106,  379,  367,    0,  368,  396,  656,  655,
      377,  385,  644,  406,  412,  844,  420,  429,  398,  651,
      434,  440,  376,  339,  629,  453,    0,  634,    0,  486,
      389,  441,  644,  641,  431,  635,  646,  426,  450,  632,
      465,  610,  459,  625,  454,  356,  466,  496,  611,  474,
        0,  464,  499,  612,  608,  477,  464,  527,    0,  591,
        0,  560,  488,  604,  510,  527,  464,  506,  600,  609,
      517,  525,  591,  539,  569,  514,  586,  520,  518,  580,
      579,  524,    0,  539,  547,  578,  577,  541,  551,  576,
      569,  571,  525,  573,  575,  572,  844,  593,  565,  561,

      597,  601,  558,  546,  606,  612,  616,  509,  620,  626,
      632,  505,  498,  487,  638,  483,  644,  648,  652,  478,
      472,  659,  666,  457,  671,  675,  679,  683,  687,  692,
      694,  695,  436,  701,  707,  714,  721,  418,  398,  358,
      355,  725,  729,  733,  737,  738,  744,  325,  749,  755,
      759,  763,  280,  265,  764,  769,  773,  779,  239,  784,
      228,  219,  788,  792,  796,  800,  148,  805,  809,  813
    } ;

static yyconst short int yy_def[371] =
    {   0,
      297,    1,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  298,  298,   18,   18,
       18,  297,  297,  297,  297,  297,  297,  297,  297,  299,
       18,  300,   18,   18,   18,   18,   18,  297,  297,  297,
      297,  297,  297,  297,  297,  301,  302,   29,   18,   18,
      303,   18,  297,  304,  301,  305,  302,  297,  304,   18,
       18,  306,   18,  307,  305,  305,  308,  309,   18,  297,
      306,  306,   18,  307,  310,  310,  307,  311,  297,  297,
      297,  297,  297,  297,  297,   70,  312,  297,  313,   76,
      314,   76,   76,  315,  315,   95,  297,  316,  316,  317,

      297,  297,  297,  297,  297,  297,  297,  318,  319,   88,
       76,  320,   95,  321,   96,   95,  322,  323,  297,  317,
      317,  297,  324,  318,  325,  319,  297,  324,   76,  326,
      327,   95,  297,  322,  322,  297,  297,  297,  297,  297,
      297,  297,  119,  328,  325,  325,  329,  326,  330,  327,
      331,   95,  332,  297,  333,  333,  328,  328,  330,  330,
      334,  334,   95,  335,  335,  297,  336,  337,  338,  334,
      339,  334,   95,  297,  340,  165,  341,  165,  165,  297,
      297,  336,  336,  342,  343,  334,  297,  297,  297,  297,
      297,  297,  297,  344,  345,  174,  165,  297,  346,  342,

      347,  343,  331,  334,  297,  348,  344,  349,  345,  297,
      348,  165,  297,  350,  350,  297,  347,  347,  334,  351,
      349,  349,  332,  352,  297,  297,  353,  215,  354,  215,
      215,  334,  351,  351,  355,  297,  297,  297,  297,  297,
      297,  297,  356,  357,  226,  215,  358,  358,  297,  297,
      359,  356,  360,  357,  297,  359,  215,  297,  361,  248,
      362,  248,  248,  363,  360,  360,  346,  364,  297,  297,
      297,  297,  297,  297,  297,  365,  366,  258,  248,  363,
      363,  297,  367,  365,  368,  366,  297,  367,  248,  369,
      368,  368,  355,  370,  369,  369,    0,  297,  297,  297,

      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297
    } ;

static yyconst short int yy_nxt[881] =
    {   0,
        4,    5,    4,    6,    7,    8,    9,   10,    4,   11,
       12,    4,    4,   13,   14,   15,   16,   17,   17,   18,
       19,   17,   17,   17,   20,   17,   17,   17,   17,   17,
       17,   21,   17,   22,   23,   24,   29,   30,   29,   30,
       35,   32,   36,   32,   37,   50,   31,   31,   31,   49,
       31,   51,   52,   31,   54,   31,   55,   32,   34,   54,
       59,   33,   54,   33,   39,   40,   54,   53,   41,   41,
       53,   41,   41,   31,   31,   60,   42,   43,   44,   54,
       31,   55,   32,   61,   54,   54,   63,   54,   31,   30,
       54,   54,   65,   32,   67,   70,   45,   39,   40,   67,

       73,   41,   48,   69,   41,   41,   31,  162,   31,   42,
       43,   44,   87,   31,   30,   68,   70,   65,   32,  297,
       72,   30,   31,   98,   65,   32,   74,  162,   67,   45,
       31,   78,   79,   80,   99,   31,   81,   81,   98,   81,
       81,   72,   88,   89,   82,   83,   84,   91,   98,   98,
       98,   88,   89,  111,   90,  290,   91,   97,   97,   98,
       90,   98,  129,   98,   85,   79,   80,   92,  119,   81,
       86,   93,   81,   81,   98,   98,   92,   82,   83,   84,
       29,  112,   29,  112,  123,  114,  118,  114,  123,  124,
       91,  128,  123,  121,  119,   72,  122,   85,   29,   30,

      122,  116,   31,   32,  132,  115,  163,  115,  133,  123,
      113,  113,   95,  123,  134,  123,  123,  123,  123,  121,
      124,   91,  155,   96,  101,  102,  277,   67,  103,  103,
       89,  103,  103,  145,   91,  276,  104,  105,  106,  165,
      123,   90,  152,  147,  148,  114,  264,  155,  113,  156,
       89,  155,  155,  145,   91,  166,  107,  101,  102,  154,
      154,  103,  110,   89,  103,  103,  145,   91,  155,  104,
      105,  106,  244,  157,  155,   67,  155,  155,  148,  114,
      112,  155,   90,  159,  114,  197,  176,  243,  169,  107,
       39,   40,  171,  155,   41,   48,  112,   41,   41,  159,

      114,  206,   42,   43,   44,  112,  168,  169,  159,  114,
      173,  171,  181,  215,  113,  174,  175,  113,  182,  176,
      177,  212,   45,  136,  137,  172,  206,  138,  138,  216,
      138,  138,  220,  174,  175,  139,  140,  141,  177,  169,
      178,  206,  169,  171,  200,  171,  171,  169,  211,  205,
      233,  171,  223,  179,  186,  142,  136,  137,  178,  204,
      138,  143,  195,  138,  138,  194,  206,  206,  139,  140,
      141,  207,  177,  206,  206,  205,  200,  171,  169,  207,
      177,  217,  171,  228,  206,  257,  121,  169,  142,  187,
      188,  171,  206,  189,  189,  165,  189,  189,  223,  206,

      219,  190,  191,  192,  175,  185,  169,  221,  177,  224,
      171,  166,  176,  226,  227,  246,  228,  232,  229,  226,
      227,  193,  187,  188,  229,  184,  189,  196,  169,  189,
      189,  217,  171,  251,  190,  191,  192,  169,  230,  231,
      217,  171,  175,  167,  230,  221,  177,  176,  175,  169,
      248,  221,  177,  171,  193,  236,  237,  251,  251,  238,
      238,  256,  238,  238,  144,  250,  249,  239,  240,  241,
      252,  229,  251,  258,  259,  252,  229,  267,  261,  131,
      250,  251,  251,  215,  251,  130,  251,  242,  236,  237,
      117,  228,  238,  245,  109,  238,  238,  251,  262,  216,

      239,  240,  241,  258,  259,  108,  251,  227,  261,  268,
      265,  229,  100,  228,  279,  260,   75,  280,  227,  267,
      242,  265,  229,  263,  283,  284,  261,  288,  262,  269,
      270,  283,  283,  271,  271,  227,  271,  271,  265,  229,
      282,  272,  273,  274,  248,  260,  283,  289,  283,  283,
      284,  261,  283,   64,  282,  259,  283,  283,  291,  261,
      249,  275,  269,  270,  293,   62,  271,  278,   47,  271,
      271,  283,   46,  294,  272,  273,  274,  259,  260,  259,
      291,  261,  291,  261,  295,  293,  293,  260,  293,  293,
      293,  287,  267,  267,  275,   31,   31,   31,   31,  287,

       31,   56,   56,  282,   56,   57,  282,   57,   57,   66,
       66,   66,  282,   66,   71,  282,   71,  267,  260,   71,
       74,  267,   74,   74,   77,  255,   77,   77,   90,   90,
       90,   90,  180,   90,   94,   94,   94,   94,  255,   94,
      113,  113,  113,  113,  250,  113,  120,  250,  120,  250,
      250,  120,  125,  125,  223,  125,  126,  223,  126,  126,
      134,  228,  235,  134,  223,  225,  134,  135,  223,  210,
      135,  203,  213,  135,  146,  146,  146,  210,  146,  149,
      149,  205,  149,  150,  205,  150,  150,  157,  205,  157,
      157,  158,  205,  158,  158,  160,  160,  160,  203,  160,

      161,  161,  164,  164,  170,  170,  170,  181,  170,  176,
      176,  176,  176,  181,  176,  182,  199,  198,  182,  176,
      113,  182,  183,  181,  180,  183,   67,   67,  183,  201,
      201,  151,  201,  202,   67,  202,  202,  208,  208,  154,
      208,  209,  154,  209,  209,  214,  214,  218,  218,  218,
      154,  218,  222,  222,  222,  154,  222,  228,  228,  228,
      228,  133,  228,  233,  133,  233,  233,  234,  153,  234,
      234,  247,  247,  253,  253,  151,  253,  254,   67,  254,
      254,  260,  260,  260,  260,  127,  260,  266,  266,  266,
      133,  266,  280,  113,  280,  280,  281,  127,  281,  281,

      285,  285,  122,  285,  286,  122,  286,  286,  292,  292,
      292,  122,  292,  295,  122,  295,  295,  296,   90,  296,
      296,   97,   97,   97,   97,   67,   67,   76,   67,   67,
       58,   58,   53,   53,   53,   53,   31,   38,   28,   27,
       26,   25,  297,    3,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297
    } ;

static yyconst short int yy_chk[881] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   17,   17,   18,   18,
       19,   17,   20,   18,   21,   35,   19,   20,   21,   34,
       34,   36,   37,   35,   41,   37,   46,   46,   18,   42,
       48,   17,   44,   18,   29,   29,   53,   42,   29,   29,
       44,   29,   29,   49,   36,   49,   29,   29,   29,   41,
       50,   55,   55,   50,   42,   48,   52,   44,   52,   56,
       59,   53,   56,   56,   60,   62,   29,   33,   33,  151,

       63,   33,   33,   61,   33,   33,   63,  151,   60,   33,
       33,   33,   73,   61,   65,   59,   71,   65,   65,  203,
       62,   66,   33,   81,   66,   66,   68,  203,   68,   33,
       69,   69,   70,   70,   86,   73,   70,   70,   97,   70,
       70,   71,   75,   75,   70,   70,   70,   75,   81,   82,
       84,   76,   76,   93,   93,  367,   76,   82,   84,   86,
      111,   99,  111,   97,   70,   72,   72,   75,  100,   72,
       72,   76,   72,   72,   82,   84,   76,   72,   72,   72,
       94,   94,   95,   95,  103,   94,   99,   95,  104,  108,
      108,  110,  106,  100,  120,   72,  104,   72,   78,   78,

      106,   95,   78,   78,  116,   94,  152,   95,  118,  103,
      116,  152,   78,  104,  118,  122,  110,  106,  128,  120,
      124,  124,  138,   78,   88,   88,  362,  129,   88,   88,
      125,   88,   88,  125,  125,  361,   88,   88,   88,  153,
      122,  129,  132,  128,  130,  130,  359,  138,  132,  143,
      145,  139,  141,  145,  145,  153,   88,   92,   92,  139,
      141,   92,   92,  146,   92,   92,  146,  146,  154,   92,
       92,   92,  354,  147,  143,  147,  139,  141,  148,  148,
      149,  156,   92,  149,  149,  179,  179,  353,  161,   92,
       96,   96,  161,  154,   96,   96,  159,   96,   96,  159,

      159,  189,   96,   96,   96,  160,  156,  162,  160,  160,
      163,  162,  168,  199,   96,  164,  164,  163,  168,  197,
      164,  197,   96,  119,  119,  162,  189,  119,  119,  199,
      119,  119,  348,  165,  165,  119,  119,  119,  165,  170,
      164,  190,  172,  170,  184,  184,  172,  186,  196,  190,
      224,  186,  224,  165,  172,  119,  121,  121,  165,  186,
      121,  121,  341,  121,  121,  340,  190,  192,  121,  121,
      121,  194,  194,  196,  205,  192,  200,  200,  201,  207,
      207,  201,  201,  246,  211,  246,  121,  204,  121,  174,
      174,  204,  192,  174,  174,  223,  174,  174,  212,  205,

      204,  174,  174,  174,  208,  339,  219,  208,  208,  211,
      219,  223,  212,  214,  214,  231,  231,  219,  214,  215,
      215,  174,  178,  178,  215,  338,  178,  178,  217,  178,
      178,  217,  217,  238,  178,  178,  178,  218,  214,  215,
      218,  218,  221,  333,  215,  221,  221,  178,  222,  232,
      235,  222,  222,  232,  178,  226,  226,  239,  238,  226,
      226,  245,  226,  226,  324,  239,  235,  226,  226,  226,
      243,  243,  241,  247,  247,  252,  252,  257,  247,  321,
      241,  250,  239,  267,  256,  320,  245,  226,  230,  230,
      316,  257,  230,  230,  314,  230,  230,  241,  247,  267,

      230,  230,  230,  248,  248,  313,  250,  253,  248,  256,
      253,  253,  312,  230,  263,  263,  308,  268,  265,  268,
      230,  265,  265,  248,  271,  276,  276,  278,  248,  258,
      258,  282,  272,  258,  258,  266,  258,  258,  266,  266,
      272,  258,  258,  258,  293,  279,  274,  279,  288,  271,
      284,  284,  278,  304,  274,  285,  282,  272,  285,  285,
      293,  258,  262,  262,  289,  303,  262,  262,  300,  262,
      262,  274,  299,  288,  262,  262,  262,  291,  289,  292,
      291,  291,  292,  292,  294,  296,  294,  262,  295,  290,
      287,  286,  281,  280,  262,  298,  298,  298,  298,  277,

      298,  301,  301,  275,  301,  302,  273,  302,  302,  305,
      305,  305,  270,  305,  306,  269,  306,  264,  260,  306,
      307,  255,  307,  307,  309,  254,  309,  309,  310,  310,
      310,  310,  249,  310,  311,  311,  311,  311,  244,  311,
      315,  315,  315,  315,  242,  315,  317,  240,  317,  237,
      236,  317,  318,  318,  234,  318,  319,  233,  319,  319,
      322,  228,  225,  322,  220,  213,  322,  323,  210,  209,
      323,  202,  198,  323,  325,  325,  325,  195,  325,  326,
      326,  193,  326,  327,  191,  327,  327,  328,  188,  328,
      328,  329,  187,  329,  329,  330,  330,  330,  185,  330,

      331,  331,  332,  332,  334,  334,  334,  183,  334,  335,
      335,  335,  335,  182,  335,  336,  181,  180,  336,  176,
      173,  336,  337,  167,  166,  337,  158,  157,  337,  342,
      342,  150,  342,  343,  144,  343,  343,  344,  344,  142,
      344,  345,  140,  345,  345,  346,  346,  347,  347,  347,
      137,  347,  349,  349,  349,  136,  349,  350,  350,  350,
      350,  135,  350,  351,  134,  351,  351,  352,  133,  352,
      352,  355,  355,  356,  356,  131,  356,  357,  127,  357,
      357,  358,  358,  358,  358,  126,  358,  360,  360,  360,
      117,  360,  363,  113,  363,  363,  364,  109,  364,  364,

      365,  365,  107,  365,  366,  105,  366,  366,  368,  368,
      368,  102,  368,  369,  101,  369,  369,  370,   90,  370,
      370,   85,   83,   80,   79,   77,   74,   67,   64,   58,
       57,   47,   45,   43,   40,   39,   31,   23,   16,   15,
       14,    6,    3,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 ".\\analizadorLexico.l"
#define INITIAL 0
#line 2 ".\\analizadorLexico.l"
#include <stdio.h>
#include <stdlib.h>
FILE    *yyin;
int     yylval;
char    *yyltext;

int yyerror(void);

#line 678 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 50 ".\\analizadorLexico.l"


#line 832 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 298 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 844 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 52 ".\\analizadorLexico.l"
printf("\nEND_LINE: %s\n", yytext);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 53 ".\\analizadorLexico.l"
printf("\nCONS: %s\n", yytext);
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 54 ".\\analizadorLexico.l"
printf("\nCONDICION: %s\n", yytext);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 55 ".\\analizadorLexico.l"
printf("\nBLOQUE: %s\n", yytext);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 56 ".\\analizadorLexico.l"
printf("\nOP ASIG: %s\n", yytext);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 57 ".\\analizadorLexico.l"
printf("\nOP SUMA: %s\n", yytext);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 58 ".\\analizadorLexico.l"
printf("\nOP MUL: %s\n", yytext);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 59 ".\\analizadorLexico.l"
printf("\nOP RES: %s\n", yytext);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 60 ".\\analizadorLexico.l"
printf("\nOP DIV: %s\n", yytext);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 61 ".\\analizadorLexico.l"
printf("\nOP LESS: %s\n", yytext);
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 62 ".\\analizadorLexico.l"
printf("\nOP MORE: %s\n", yytext);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 63 ".\\analizadorLexico.l"
printf("\nOP EQ: %s\n", yytext);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 64 ".\\analizadorLexico.l"
printf("\nOP LEQ: %s\n", yytext);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 65 ".\\analizadorLexico.l"
printf("\nOP MOQ: %s\n", yytext);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 66 ".\\analizadorLexico.l"
printf("\nOP EQQ: %s\n", yytext);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 67 ".\\analizadorLexico.l"
printf("\nOP AND: %s\n", yytext);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 68 ".\\analizadorLexico.l"
printf("\nOP OR: %s\n", yytext);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 69 ".\\analizadorLexico.l"
printf("\nLLAVE: %s\n", yytext);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 70 ".\\analizadorLexico.l"
printf("\nEND LLAVE: %s\n", yytext);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 71 ".\\analizadorLexico.l"
printf("\nPARENTESIS: %s\n", yytext);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 72 ".\\analizadorLexico.l"
printf("\nEND PARENTESIS: %s\n", yytext);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 73 ".\\analizadorLexico.l"
printf("\nOP DEC: %s\n", yytext);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 74 ".\\analizadorLexico.l"
printf("\nIF: %s\n", yytext);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 75 ".\\analizadorLexico.l"
printf("\nWHILE: %s\n", yytext);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 77 ".\\analizadorLexico.l"
yyerror();
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 79 ".\\analizadorLexico.l"
ECHO;
	YY_BREAK
#line 1045 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 298 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 298 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 297);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 79 ".\\analizadorLexico.l"


int main(int argc, char *argv[])
{
    if ((yyin = fopen(argv[1], "rt")) == NULL)
    {
        printf("\nNo se puede abrir el archivo: %s\n", argv[1]);
    }
    else
    {
        yylex();
    }
fclose(yyin);
}

int yyerror(void)
{
    printf("Error lexico, caracter invalido %s\n", yytext);
    exit(1);
}